# ================== CONFIGURACIÓN DE MONGODB ==================
# URI de conexión a la base de datos MongoDB (local en este caso)
spring.data.mongodb.uri=mongodb://localhost:27017/criminalReport

# Nivel de detalle de los logs para operaciones con MongoTemplate (útil para depuración)
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG


# ================== CONFIGURACIÓN DEL SERVIDOR ==================
# Puerto en el que se ejecuta la aplicación Spring Boot
server.port=8081


# ================== CONFIGURACIÓN DEL CORREO (Valores tomados del .env) ==================
# Host del servidor SMTP (Gmail)
mail.smtp.host=smtp.gmail.com

# Puerto SMTP para conexiones seguras TLS/STARTTLS. El más usado y recomendado por gmail
mail.smtp.port=587

# Correo desde el cual se enviarán los mensajes

mail.smtp.username=proavanzada@gmail.com

# Contraseña de la cuenta de correo (se recomienda mover esto a variables de entorno)

mail.smtp.password=Avanzada1.

jwt.secret=claveSecreta123


